trigger:
  branches:
    include:
    - '*'
  tags:
    include:
    - '*'

variables:
  CKBClientVersion: v0.31.0

jobs:
  - job: UnitTest
    pool:
      vmImage: 'windows-2019'
    steps:
      - template: devtools/azure/windows-dependencies.yml
        parameters:
          rustup_toolchain: '1.41.0-x86_64-pc-windows-msvc'
      - script: make test
        displayName: Run unit tests
        env:
          CI: true

  - job: IntegrationTest
    timeoutInMinutes: 0
    pool:
      vmImage: 'windows-2019'
    steps:
      - template: devtools/azure/windows-dependencies.yml
        parameters:
          rustup_toolchain: '1.41.0-x86_64-pc-windows-msvc'
      - script: make CKB_TEST_SEC_COEFFICIENT=5 CKB_TEST_ARGS="--max-time 1200 -c 4" integration-windows
        displayName: Run integration tests
        env:
          CI: true

  - job: Package
    timeoutInMinutes: 0
    pool:
      vmImage: 'windows-2019'
    steps:
      - template: devtools/azure/windows-dependencies.yml
        parameters:
          rustup_toolchain: '1.41.0-x86_64-pc-windows-msvc'
      - script: make prod
        displayName: Build
